id = 4
title = "两点之间的距离"
description = '''
写一个程序，用来计算平面上两个点 $(x_1,y_1)$ 和 $(x_2,y_2)$ 之间的距离。距离公式采用：

$ \sqrt{(x_1-x_2)^2+(y_1-y_2)^2} $

（题目与测试数据来自厦门大学 COJ，感谢出题者的付出！）
'''
instruction = '''
### 输入

空格隔开的4个浮点数，分别表示$x_1、y_1、x_2、y_2$。

### 输出

一个浮点数，表示距离，保留6位小数。

### 新手提示

如何进行数学运算？如何处理浮点数？如何保留小数位数？

查询搜索引擎，或者阅读文档。
'''
accepted_languages = ["c", "cpp", "python"]
flag = "ZFun{5_Centimeters_Per_Second_{hash}}"

[limit]
time = 1 # in s
memory = 256 # in mb

[[samples]]
stdin = '''
0 0 3 4
'''
stdout = '''
5.000000
'''
